# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BookResearchApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BookResearchApp

pod 'Alamofire', '~> 5.2'
pod 'SwiftyJSON', '~> 4.0'
pod 'VerticalCardSwiper'
pod 'SDWebImage', '~> 5.0'
pod 'PKHUD', '~> 5.0' 
pod 'DropDown'
end
